# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports :
      - 5432:5432
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 198788
      POSTGRES_USER : SMAUG
        
        #sert a faire l'interface web pour la gestion si gestionnaire BDD(dbeaver ... alors pas besoin)

        # adminer:
        #image: adminer
        #restart: always
        #ports:
      # si port utilisé ou à modifier faire sur le 1er 8080
      #- 8080:8080
